### ISSUE TITLE
Make options more generics

### ISSUE THREAD

**Issue by evilz** [MangelMaxime/Fable.Elmish.Bulma#31]
I don't know if this is possible but a like to have common module for common stuff like colors and size.

So this 

```fsharp 
Button.button [ Button.isSmall ] [ str "Small" ]
```

can be

```fsharp
Button.button [ Size.small ] [ str "Small" ]
```

or

```fsharp
Button.button [ Option.small ] [ str "Small" ]
```

Can be inspirated from http://package.elm-lang.org/packages/debois/elm-mdl/8.1.0/Material-Options

What do you think ?

**Comment by MangelMaxime** [comment]
With the current implementation it's not possible.

As each file define it's own `Option` types fully. By that I mean , that I don't make them inherit from interface (it's something I tried in the first versions of the lib and it's was harder to maintain and write new components also, you have a lot of exception case to handle.)

Each helpers is redefine locally for the specify option.
For example, for `Delete.fs`:

So I would tend to refuse this kind of compromise.

```fs
    let isSmall = Size IsSmall
    let isMedium = Size IsMedium
    let isLarge = Size IsLarge
```

where `IsSmall, IsMedium, IsLarge` is indead a generic type located into `Common.fs`.

The design idea of this lib, is also to help you find what you can use or not on a component. For example, by typing `Button.` you get access to all the customization of the component. You don't need to check the bulma docs or know that a button can have size properties. This choice has been made to increase your productivity and have an easier learning curve.
Also, Button can have the size property `is-full-width` which is not a standard size in Bulma so you would need to know the exception case.

Finally, implementing something equivalent to what you show from your link would increase the complexity of writing a component And need a lot of refactoring, rewrite and a lot of breaking change in current users code.

**Comment by alfonsogarciacaro** [comment]
I agree with @MangelMaxime that having specific options for each component helps exploratory programming (you just need to type the element name and the available options are available). Having generic options for all elements can be also confusing because, though most of them have four sizes available, this is not true for all of them. @MangelMaxime already shows an example above (`is-full-width`), other differences are:

- Some elements don't have different sizes: like `Box`.
- In some cases, size has different semantics: with `Content` it modifies the font size, we can add this in the comment.
- Other elements have more sizes available: like `Title` with 6.

**Comment by evilz** [comment]
OK nice, I close this.
